name: braand_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  geolocator: ^10.1.0
  supabase_flutter: ^2.0.0
  camera: ^0.10.5+9
  image_picker: ^1.0.7

  device_info_plus: ^9.1.1
  excel: ^4.0.6
  pdf: ^3.11.3
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"

flutter:
  uses-material-design: true
